version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classroom
    ports: ["5432:5432"]
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d classroom || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 5s

  pgweb:
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@db:5432/classroom?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports: ["8081:8081"]
    command: ["--bind=0.0.0.0", "--listen=8081"]
volumes:
  pgdata:
